project:
  type: website
  output-dir: docs

website:
  title: "Kyeonghwany"
  
  site-url: 'https://kyeonghwany.github.io'
  site-path: '/'
  search: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
        
  comments:
    giscus:
      repo: kyeonghwany/kyeonghwany.github.io
      language: ko

format:
  html:
    template: template.html
    include-in-header: gtm-header.html
    include-before-body: gtm-body.html
    theme:
      - minty
      - custom.scss
    toc: true
    code-fold: true
    code-tools: true
    code-copy: true
    code-line-numbers: false
    code-block-background: true
    

execute:
  freeze: auto
