project:
  type: website
  output-dir: docs

website:
  title: "Kyeonghwany Blog"
  site-url: 'https://kyeonghwany.github.io'
  site-path: '/'
  
  search: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: project.qmd
        text: Project
      - href: mytip.qmd
        text: Mytip
      - href: about.qmd
        text: Portfolio
        
  comments: 
    giscus:
      repo: kyeonghwany/kyeonghwany.github.io
      language: ko
      
  google-analytics: "G-NDDS4J9T4S"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

