project:
  type: website
  output-dir: docs

website:
  title: "Kyeonghwany Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: side_project.qmd
        text: Side Project
      - href: mytip.qmd
        text: Mytip
      - href: about.qmd
        text: Portfolio

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

