project:
  type: website
  output-dir: docs

website:
  title: "kyeonghwany blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: portfolio
      - href: posts.qmd
        text: posts

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

