---
title: "전라북도 공공데이터 품질관리 프로젝트"
description: 공공데이터 품질관리에 대한 개념과 제가 경험한 평가 대응 방법을 공유합니다.
author: "김경환"
date: 2024-04-16
date-modified: last-modified
categories:
  - 공공데이터
  - 데이터 표준화
  - 데이터 품질관리
---

2023년 7월, 전라북도 공공데이터 품질관리 용역를 수행했습니다. 결론적으로 중요 지표였던 **공공데이터 품질관리 수준평가 96점을 달성**하여 전라북도청 평가점수 최고점을 갱신했습니다. 데이터 표준화와 데이터 품질관리에 대한 실무를 접할 수 있어서 저에게도 유익한 사업이었습니다.

## 품질관리 수준평가란?

정부에서는 매년 공공데이터법 제9조에 근거하여 공공데이터 개방, 활용, 품질 및 관리체계 등 공공데이터 제공 및 운영에 관한 실태를 파악하고 개선하기 위해 "공공데이터 제공 운영실태 평가"를 실시하고 있습니다.

공공데이터 품질관리 수준평가는 공공데이터 제공 운영실태 평가 중 35점을 반영합니다.

| 평가영역                     | 배점(광역 기관 기준) |
|------------------------------|----------------------|
| 관리체계                     | 7                    |
| 개방                         | 35                   |
| 활용                         | 23                   |
| **공공데이터 품질관리 수준** | 35                   |
| 기타                         | -1/건당              |
: 공공데이터 제공 운영실태 평가 지표 {.hover .bordered}

품질관리 수준평가는 공공기관이 관리하는 데이터에 대한 일정 수준의 품질을 확보하기 위한 데이터 관리체계를 잘 갖추고 데이터 품질수준을 파악하기 위해 실시하고 있습니다.

| 번호        | 지표                                          | 배점 |
|-------------|-----------------------------------------------|------|
| 1           | 품질진단 절차 별 일정 준수                    | 2    |
| 2           | 품질관리 계획수립                             | 2    |
| 3           | 예방적 품질관리 진단                          | 12   |
| 4           | **데이터 표준 확산**                          | 10   |
| 5           | **데이터 구조 안정화**                        | 6    |
| 6           | **데이터 연계관리**                           | 8    |
| 7           | **데이터 품질진단**                           | 20   |
| 8           | **품질진단 결과조치**                         | 20   |
| 9           | **데이터 오류율**                             | 14   |
| 10          | 오류신고 요구사항 분석 및 개선                | 4    |
| 11          | 개방 데이터 품질수준                          | 2    |
| 가점 지표 1 | 예방적품질관리 진단 및 주요DB 품질진단 컨설팅 | 2    |
| 가점 지표 2 | 대상 DB 35개 초과 선정 및 진단                | 3    |
: 공공데이터 품질관리 수준평가 지표 {.hover .bordered}

위 지표 중 4\~9번 지표는 기관에서 관리하는 정보시스템에 대한 **DB의 품질을 평가**하는데 목적이 있으며 평가에 대응하기 위해서는 **데이터 표준화와 데이터 품질관리**에 대한 이해가 필요합니다.

## 데이터 표준화

데이터 표준화에 대한 내용은 구글링을 통해 쉽게 찾아낼 수 있습니다. 정확한 개념과 이론을 이해하기 위해서는 다음 페이지가 가장 도움이 됩니다.

-   [Data on-air DA 가이드](https://dataonair.or.kr/db-tech-reference/d-guide/da-guide/) : 데이터 표준화에 대한 개념과 일반적인 데이터 표준화 프로세스를 알 수 있습니다.

-   [공공데이터베이스 표준화 관리 매뉴얼](https://gooddata.kmaclxp.co.kr/gnu/bbs/board.php?bo_table=notice&wr_id=295) : 공공데이터에 대한 표준화 관리 방법을 알 수 있습니다.

[Data on-air DA 가이드-데이터 표준화 개념](https://dataonair.or.kr/db-tech-reference/d-guide/da-guide/?pageid=6&mod=document&uid=269)에 따르면, **데이터 표준화는 시스템별로 산재해 있는 데이터 정보 요소에 대한 명칭, 정의, 형식, 규칙에 대한 원칙을 수립하여 이를 전사적으로 적용하는 것**으로 정의하고 있습니다.

DB를 예로 들면 테이블을 생성할 때 다음과 같은 SQL을 통해 생성합니다.

``` sql
create table 테이블이름 (
    컬럼이름1 데이터유형1 제약조건1,
    컬럼이름2 데이터유형2 제약조건2,
    ...
);
```

표준화 체계가 있는 기업/기관에서는 임의로 컬럼이름, 데이터유형, 제약조건 등을 만들지 않고 정해진 표준에 따라 컬럼을 만들어야합니다.

이처럼 표준을 정의하고 DB에 반영하는 과정을 통해 기업/기관 내 사용하는 정보시스템의 DB가 모두 표준을 따르게 됩니다.

## 데이터 표준화가 필요한 이유

+-------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+
| 데이터 표준화 미적용                                                                                              | 데이터 표준화 적용                                                      |
+===================================================================================================================+=========================================================================+
| -   **컬럼명 의미 혼재**                                                                                          | -   **컬럼명 통일**                                                     |
|                                                                                                                   |                                                                         |
|     -   컬럼명이 동일하지만 의미가 다르거나 의미는 같지만 컬럼명이 다른 경우가 존재                               |     -   동일한 의미의 데이터는 동일한 명칭을 사용                       |
|                                                                                                                   |                                                                         |
|     -   의사소통에 문제가 발생                                                                                    |     -   원활한 의사소통 가능                                            |
+-------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+
| -   **필요 데이터 위치 파악 문제**                                                                                | -   **필요 데이터 위치 파악 원활**                                      |
|                                                                                                                   |                                                                         |
|     -   정해진 표준이 없기 때문에 필요한 정보가 무슨 컬럼명으로 정의되어 있는지 파악하는데 시간이 소요            |     -   표준에 따라 필요한 데이터의 위치를 쉽게 파악 가능               |
+-------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+
| -   **데이터 통합의 어려움**                                                                                      | -   **데이터 통합 용이**                                                |
|                                                                                                                   |                                                                         |
|     -   데이터 결합 시 데이터 의미 파악에 많은 시간을 사용                                                        |     -   정의된 표준을 이해하고 있으면 데이터 의미 파악에 드는 시간 감소 |
|                                                                                                                   |                                                                         |
|     -   같은 의미의 컬럼을 결합 시 사용되는 데이터 형식, 단위, 코드값이 다를 수 있기 때문에 추가 정제 작업이 필요 |     -   같은 의미의 컬럼을 결합 시 추가 정제 작업이 필요 없음           |
+-------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+
| -   **데이터 품질 문제**                                                                                          | -   **데이터 품질 향상**                                                |
|                                                                                                                   |                                                                         |
|     -   컬럼에 대한 도메인이 정의되지 않음                                                                        |     -   컬럼에 대한 도메인이 명확하게 정의                              |
|                                                                                                                   |                                                                         |
|     -   오류 데이터가 입력될 가능성 높음                                                                          |     -   오류 데이터가 입력될 가능성이 낮음                              |
+-------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+
: {tbl-colwidths="[50,50]" .hover .bordered}

## 데이터 표준화 요소

## 데이터 품질관리
